export { default as BlocksRenderer } from './src/BlocksRenderer.astro';

export type {
  BlocksContent,
  BlocksRendererProps,
  BlockNode,
  TextNode,
  LinkNode,
  InlineNode,
  ParagraphNode,
  HeadingNode,
  ListNode,
  ListItemNode,
  QuoteNode,
  CodeNode,
  ImageNode,
  HorizontalLineNode,
  TableNode,
  TableRowNode,
  TableCellNode,
  TableHeaderCellNode,
  TableCellAlign,
  MediaEmbedNode,
  MathNode,
  DiagramNode,
  DiagramTheme,
  DiagramThemeName,
  DiagramColors,
  CalloutNode,
  CalloutVariant,
  DetailsNode,
  ButtonElement,
  ButtonAlignment,
  ButtonLink,
  ButtonFile,
  ButtonStyle,
  SocialEmbedNode,
  SocialPlatform,
  SocialEmbedAlignment,
  SocialEmbedOembed,
  AudioNode,
  AudioAlignment,
  AudioFile,
  AudioPlayer,
  AudioPreload,
  MediaAlignment,
  MediaAspectRatio,
  EmbedNode,
  EmbedProvider,
  VideoNode,
  VideoProvider,
  VideoFile,
  VideoPlayer,
  TextAlign,
  StyleValue,
  CustomBlocksConfig,
  CustomModifiersConfig,
  AstroComponentFactory,
  // Registering a block type from another package. These were reachable only
  // through the source before, which made `blockPlugins` a prop nobody outside
  // could give a type to.
  AstroBlockPlugin,
  BlockDefinition,
  CustomBlockNode,
  AnyBlockNode,
  ExtendedBlocksContent,
} from './src/types';
